[package]
name        = "tgcalls"
version.workspace   = true
edition.workspace   = true
authors.workspace   = true
license.workspace   = true
description = "Telegram voice and video calls, powered by NTgCalls."
repository.workspace = true
keywords    = ["telegram", "calls", "voip", "webrtc", "ntgcalls"]
categories  = ["api-bindings", "multimedia"]
readme      = "README.md"

[features]
default  = ["bundled"]
bundled  = ["ntgcalls/bundled"]

[dependencies]
ntgcalls = { path = "../ntgcalls", version = "0.1.0" }
tracing     = "0.1"
