[package]
name        = "ntgcalls"
version.workspace   = true
edition.workspace   = true
authors.workspace   = true
license.workspace   = true
description = "Raw FFI bindings to the NTgCalls C API"
repository.workspace = true
readme      = "README.md"
exclude     = ["lib/include/*"]
links       = "ntgcalls"

[features]
default  = ["bundled"]
bundled  = []
